version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/react-native-fbads

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-native-fbads
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run: |
          yarn install --frozen-lockfile
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-native-fbads
      - run: |
          yarn lint
  flow:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-native-fbads
      - run: |
          yarn flow
workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
